/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VettingRouteImport } from './routes/vetting'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHermesRunRouteImport } from './routes/api/hermes-run'
import { Route as ApiFocusGroupStreamRouteImport } from './routes/api/focus-group-stream'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedHermesRouteImport } from './routes/_authenticated/hermes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSysadminIndexRouteImport } from './routes/_authenticated/sysadmin.index'
import { Route as AuthenticatedHermesIndexRouteImport } from './routes/_authenticated/hermes.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedHermesSettingsRouteImport } from './routes/_authenticated/hermes.settings'
import { Route as AuthenticatedHermesNewRouteImport } from './routes/_authenticated/hermes.new'
import { Route as AuthenticatedHermesAgentsRouteImport } from './routes/_authenticated/hermes.agents'
import { Route as AuthenticatedHermesTaskIdRouteImport } from './routes/_authenticated/hermes.$taskId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSkillsRouteImport } from './routes/_authenticated/admin.skills'
import { Route as AuthenticatedAdminPromptTemplatesRouteImport } from './routes/_authenticated/admin.prompt-templates'
import { Route as AuthenticatedAdminHermesPresetsRouteImport } from './routes/_authenticated/admin.hermes-presets'
import { Route as AuthenticatedAdminDeployRouteImport } from './routes/_authenticated/admin.deploy'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin.audit-log'

const VettingRoute = VettingRouteImport.update({
  id: '/vetting',
  path: '/vetting',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesRunRoute = ApiHermesRunRouteImport.update({
  id: '/api/hermes-run',
  path: '/api/hermes-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFocusGroupStreamRoute = ApiFocusGroupStreamRouteImport.update({
  id: '/api/focus-group-stream',
  path: '/api/focus-group-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHermesRoute = AuthenticatedHermesRouteImport.update({
  id: '/hermes',
  path: '/hermes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSysadminIndexRoute =
  AuthenticatedSysadminIndexRouteImport.update({
    id: '/sysadmin/',
    path: '/sysadmin/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHermesIndexRoute =
  AuthenticatedHermesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHermesRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHermesSettingsRoute =
  AuthenticatedHermesSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedHermesRoute,
  } as any)
const AuthenticatedHermesNewRoute = AuthenticatedHermesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedHermesRoute,
} as any)
const AuthenticatedHermesAgentsRoute =
  AuthenticatedHermesAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedHermesRoute,
  } as any)
const AuthenticatedHermesTaskIdRoute =
  AuthenticatedHermesTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => AuthenticatedHermesRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSkillsRoute =
  AuthenticatedAdminSkillsRouteImport.update({
    id: '/admin/skills',
    path: '/admin/skills',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPromptTemplatesRoute =
  AuthenticatedAdminPromptTemplatesRouteImport.update({
    id: '/admin/prompt-templates',
    path: '/admin/prompt-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminHermesPresetsRoute =
  AuthenticatedAdminHermesPresetsRouteImport.update({
    id: '/admin/hermes-presets',
    path: '/admin/hermes-presets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDeployRoute =
  AuthenticatedAdminDeployRouteImport.update({
    id: '/admin/deploy',
    path: '/admin/deploy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/admin/audit-log',
    path: '/admin/audit-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/intake': typeof IntakeRoute
  '/vetting': typeof VettingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hermes': typeof AuthenticatedHermesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/focus-group-stream': typeof ApiFocusGroupStreamRoute
  '/api/hermes-run': typeof ApiHermesRunRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/deploy': typeof AuthenticatedAdminDeployRoute
  '/admin/hermes-presets': typeof AuthenticatedAdminHermesPresetsRoute
  '/admin/prompt-templates': typeof AuthenticatedAdminPromptTemplatesRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/hermes/$taskId': typeof AuthenticatedHermesTaskIdRoute
  '/hermes/agents': typeof AuthenticatedHermesAgentsRoute
  '/hermes/new': typeof AuthenticatedHermesNewRoute
  '/hermes/settings': typeof AuthenticatedHermesSettingsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/hermes/': typeof AuthenticatedHermesIndexRoute
  '/sysadmin/': typeof AuthenticatedSysadminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/intake': typeof IntakeRoute
  '/vetting': typeof VettingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/focus-group-stream': typeof ApiFocusGroupStreamRoute
  '/api/hermes-run': typeof ApiHermesRunRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/deploy': typeof AuthenticatedAdminDeployRoute
  '/admin/hermes-presets': typeof AuthenticatedAdminHermesPresetsRoute
  '/admin/prompt-templates': typeof AuthenticatedAdminPromptTemplatesRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/hermes/$taskId': typeof AuthenticatedHermesTaskIdRoute
  '/hermes/agents': typeof AuthenticatedHermesAgentsRoute
  '/hermes/new': typeof AuthenticatedHermesNewRoute
  '/hermes/settings': typeof AuthenticatedHermesSettingsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/hermes': typeof AuthenticatedHermesIndexRoute
  '/sysadmin': typeof AuthenticatedSysadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/intake': typeof IntakeRoute
  '/vetting': typeof VettingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hermes': typeof AuthenticatedHermesRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/focus-group-stream': typeof ApiFocusGroupStreamRoute
  '/api/hermes-run': typeof ApiHermesRunRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/deploy': typeof AuthenticatedAdminDeployRoute
  '/_authenticated/admin/hermes-presets': typeof AuthenticatedAdminHermesPresetsRoute
  '/_authenticated/admin/prompt-templates': typeof AuthenticatedAdminPromptTemplatesRoute
  '/_authenticated/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/hermes/$taskId': typeof AuthenticatedHermesTaskIdRoute
  '/_authenticated/hermes/agents': typeof AuthenticatedHermesAgentsRoute
  '/_authenticated/hermes/new': typeof AuthenticatedHermesNewRoute
  '/_authenticated/hermes/settings': typeof AuthenticatedHermesSettingsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/hermes/': typeof AuthenticatedHermesIndexRoute
  '/_authenticated/sysadmin/': typeof AuthenticatedSysadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/intake'
    | '/vetting'
    | '/dashboard'
    | '/hermes'
    | '/settings'
    | '/api/focus-group-stream'
    | '/api/hermes-run'
    | '/admin/audit-log'
    | '/admin/deploy'
    | '/admin/hermes-presets'
    | '/admin/prompt-templates'
    | '/admin/skills'
    | '/admin/users'
    | '/hermes/$taskId'
    | '/hermes/agents'
    | '/hermes/new'
    | '/hermes/settings'
    | '/api/public/health'
    | '/admin/'
    | '/hermes/'
    | '/sysadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/intake'
    | '/vetting'
    | '/dashboard'
    | '/settings'
    | '/api/focus-group-stream'
    | '/api/hermes-run'
    | '/admin/audit-log'
    | '/admin/deploy'
    | '/admin/hermes-presets'
    | '/admin/prompt-templates'
    | '/admin/skills'
    | '/admin/users'
    | '/hermes/$taskId'
    | '/hermes/agents'
    | '/hermes/new'
    | '/hermes/settings'
    | '/api/public/health'
    | '/admin'
    | '/hermes'
    | '/sysadmin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/intake'
    | '/vetting'
    | '/_authenticated/dashboard'
    | '/_authenticated/hermes'
    | '/_authenticated/settings'
    | '/api/focus-group-stream'
    | '/api/hermes-run'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/deploy'
    | '/_authenticated/admin/hermes-presets'
    | '/_authenticated/admin/prompt-templates'
    | '/_authenticated/admin/skills'
    | '/_authenticated/admin/users'
    | '/_authenticated/hermes/$taskId'
    | '/_authenticated/hermes/agents'
    | '/_authenticated/hermes/new'
    | '/_authenticated/hermes/settings'
    | '/api/public/health'
    | '/_authenticated/admin/'
    | '/_authenticated/hermes/'
    | '/_authenticated/sysadmin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  IntakeRoute: typeof IntakeRoute
  VettingRoute: typeof VettingRoute
  ApiFocusGroupStreamRoute: typeof ApiFocusGroupStreamRoute
  ApiHermesRunRoute: typeof ApiHermesRunRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vetting': {
      id: '/vetting'
      path: '/vetting'
      fullPath: '/vetting'
      preLoaderRoute: typeof VettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-run': {
      id: '/api/hermes-run'
      path: '/api/hermes-run'
      fullPath: '/api/hermes-run'
      preLoaderRoute: typeof ApiHermesRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/focus-group-stream': {
      id: '/api/focus-group-stream'
      path: '/api/focus-group-stream'
      fullPath: '/api/focus-group-stream'
      preLoaderRoute: typeof ApiFocusGroupStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hermes': {
      id: '/_authenticated/hermes'
      path: '/hermes'
      fullPath: '/hermes'
      preLoaderRoute: typeof AuthenticatedHermesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sysadmin/': {
      id: '/_authenticated/sysadmin/'
      path: '/sysadmin'
      fullPath: '/sysadmin/'
      preLoaderRoute: typeof AuthenticatedSysadminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hermes/': {
      id: '/_authenticated/hermes/'
      path: '/'
      fullPath: '/hermes/'
      preLoaderRoute: typeof AuthenticatedHermesIndexRouteImport
      parentRoute: typeof AuthenticatedHermesRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hermes/settings': {
      id: '/_authenticated/hermes/settings'
      path: '/settings'
      fullPath: '/hermes/settings'
      preLoaderRoute: typeof AuthenticatedHermesSettingsRouteImport
      parentRoute: typeof AuthenticatedHermesRoute
    }
    '/_authenticated/hermes/new': {
      id: '/_authenticated/hermes/new'
      path: '/new'
      fullPath: '/hermes/new'
      preLoaderRoute: typeof AuthenticatedHermesNewRouteImport
      parentRoute: typeof AuthenticatedHermesRoute
    }
    '/_authenticated/hermes/agents': {
      id: '/_authenticated/hermes/agents'
      path: '/agents'
      fullPath: '/hermes/agents'
      preLoaderRoute: typeof AuthenticatedHermesAgentsRouteImport
      parentRoute: typeof AuthenticatedHermesRoute
    }
    '/_authenticated/hermes/$taskId': {
      id: '/_authenticated/hermes/$taskId'
      path: '/$taskId'
      fullPath: '/hermes/$taskId'
      preLoaderRoute: typeof AuthenticatedHermesTaskIdRouteImport
      parentRoute: typeof AuthenticatedHermesRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/skills': {
      id: '/_authenticated/admin/skills'
      path: '/admin/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AuthenticatedAdminSkillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/prompt-templates': {
      id: '/_authenticated/admin/prompt-templates'
      path: '/admin/prompt-templates'
      fullPath: '/admin/prompt-templates'
      preLoaderRoute: typeof AuthenticatedAdminPromptTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/hermes-presets': {
      id: '/_authenticated/admin/hermes-presets'
      path: '/admin/hermes-presets'
      fullPath: '/admin/hermes-presets'
      preLoaderRoute: typeof AuthenticatedAdminHermesPresetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/deploy': {
      id: '/_authenticated/admin/deploy'
      path: '/admin/deploy'
      fullPath: '/admin/deploy'
      preLoaderRoute: typeof AuthenticatedAdminDeployRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedHermesRouteChildren {
  AuthenticatedHermesTaskIdRoute: typeof AuthenticatedHermesTaskIdRoute
  AuthenticatedHermesAgentsRoute: typeof AuthenticatedHermesAgentsRoute
  AuthenticatedHermesNewRoute: typeof AuthenticatedHermesNewRoute
  AuthenticatedHermesSettingsRoute: typeof AuthenticatedHermesSettingsRoute
  AuthenticatedHermesIndexRoute: typeof AuthenticatedHermesIndexRoute
}

const AuthenticatedHermesRouteChildren: AuthenticatedHermesRouteChildren = {
  AuthenticatedHermesTaskIdRoute: AuthenticatedHermesTaskIdRoute,
  AuthenticatedHermesAgentsRoute: AuthenticatedHermesAgentsRoute,
  AuthenticatedHermesNewRoute: AuthenticatedHermesNewRoute,
  AuthenticatedHermesSettingsRoute: AuthenticatedHermesSettingsRoute,
  AuthenticatedHermesIndexRoute: AuthenticatedHermesIndexRoute,
}

const AuthenticatedHermesRouteWithChildren =
  AuthenticatedHermesRoute._addFileChildren(AuthenticatedHermesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHermesRoute: typeof AuthenticatedHermesRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminDeployRoute: typeof AuthenticatedAdminDeployRoute
  AuthenticatedAdminHermesPresetsRoute: typeof AuthenticatedAdminHermesPresetsRoute
  AuthenticatedAdminPromptTemplatesRoute: typeof AuthenticatedAdminPromptTemplatesRoute
  AuthenticatedAdminSkillsRoute: typeof AuthenticatedAdminSkillsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedSysadminIndexRoute: typeof AuthenticatedSysadminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHermesRoute: AuthenticatedHermesRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedAdminDeployRoute: AuthenticatedAdminDeployRoute,
  AuthenticatedAdminHermesPresetsRoute: AuthenticatedAdminHermesPresetsRoute,
  AuthenticatedAdminPromptTemplatesRoute:
    AuthenticatedAdminPromptTemplatesRoute,
  AuthenticatedAdminSkillsRoute: AuthenticatedAdminSkillsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedSysadminIndexRoute: AuthenticatedSysadminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  IntakeRoute: IntakeRoute,
  VettingRoute: VettingRoute,
  ApiFocusGroupStreamRoute: ApiFocusGroupStreamRoute,
  ApiHermesRunRoute: ApiHermesRunRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
